library('DBI')
library('RPostgreSQL')
library('timeDate')
library('lattice')
library("dplyr")
library("PivotalR")
library("data.table")
library("rpart")
library("rpart.plot")
library("norm")
library("ggplot2")
library("ggvis")
library("rbokeh")
library("stringr")
library("rms")
library("MASS")
library("mi")
library("randomForest")
library("caret")
library("glmnet")
library("reshape2")
library("Amelia")
library("vcd")
library("rio")
library("jsonlite")
library("Rserve");
Rserve()

## Load the necessary libraries
# library("rms")
# library("MASS")
# library("mi")
# library("randomForest")
# library("caret")
# library("glmnet")
# library("PivotalR")
# library("RPostgreSQL")
# library("reshape2")

#######################
