# Connect to GPDB
library(PivotalR)
cid <- db.connect(
  dbname = "get_data",
  user = "502585653",
  password = pswd,
  host = "3.48.35.24",
  port = 5432,
  verbose = FALSE,
  quick = TRUE
)

#Creating R object and pasting SQL query to it
query = paste("select * from reliance.insp_link_to_sns_chapter limit 10",
              sep = "")

#Saving the query output which was generated by db.q to a R object
reliance.insp_link_to_sns_chapter = db.q(query, conn.id = cid)

#Creating json using rio
library(rio)
export(reliance.insp_link_to_sns_chapter, "dbtable.json")

#Creating json using jsonlite
library(jsonlite)
dbtable1 = toJSON(reliance.insp_link_to_sns_chapter, pretty = T)
cat(dbtable1)
